(function(g){var window=this;'use strict';var V3=function(a){a.ra("cardstatechange",a.Gk()&&a.Ro()?1:0)},W3=function(a,b){var c=g.Wa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Bib=function(a){var b=g.Mr(a);
a=g.Pr(a);return new g.Br(b.x,b.y,a.width,a.height)},Cib=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.XC(a,b,function(){g.YC(e);c.apply(a,arguments)},d)},Z3=function(a){a=g.ab(a);
delete X3[a];g.id(X3)&&Y3&&Y3.stop()},Eib=function(){Y3||(Y3=new g.fu(function(){Dib()},20));
var a=Y3;a.isActive()||a.start()},Dib=function(){var a=g.eb();
g.Tc(X3,function(b){Fib(b,a)});
g.id(X3)||Eib()},$3=function(a,b,c,d){g.Du.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.S=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Fib=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Gib(a,a.progress);1==a.progress?(a.j=0,Z3(a),a.onFinish(),a.rr()):a.isPlaying()&&a.RK()},Gib=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.S[c]-a.B[c])*b+a.B[c]},Hib=function(a,b){g.xb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},a4=function(a,b,c,d,e){$3.call(this,b,c,d,e);
this.element=a},Iib=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
a4.call(this,a,b,c,d,e)},Jib=function(a){return Math.pow(a,3)},Kib=function(a){return 3*a*a-2*a*a*a},Lib=function(a){g.J.call(this);
this.B=a||window;this.j=[]},b4=function(a){return a.baseUrl||null},c4=function(a,b){return g.zs(g.dq(a,b),function(c){return!!c})},Mib=function(a,b,c){function d(na){var ia=na.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var Aa=f(ia.unsubscribedButtonText),X=f(ia.subscribedButtonText);if(ia.subscribed){var wa=f(ia.subscriberCountWithUnsubscribeText);var ca=f(ia.subscriberCountText)}else wa=f(ia.subscriberCountText),ca=f(ia.subscriberCountWithSubscribeText);var Ra=null;if(na.signinEndpoint){Ra=W3(na,"signinEndpoint","webNavigationEndpointData","url");if(!Ra){var y,W;Ra=null==(W=g.S(null==(y=ia.signInEndpoint)?void 0:y.commandMetadata,g.M2))?void 0:
W.url}if(!Ra)return null}return Aa&&(X||Ra)?{subscribed:ia.subscribed,subscribeText:Aa,subscribeCount:wa,unsubscribeText:X,unsubscribeCount:ca,enabled:ia.enabled,signinUrl:Ra,classic:na.useClassicSubscribeButton}:null}
function e(na){if(na){var ia=[],Aa=na.videoId;Aa&&ia.push("v="+Aa);(Aa=na.playlistId)&&ia.push("list="+Aa);(na=na.startTimeSeconds)&&ia.push("t="+na);return"/watch?"+ia.join("&")}}
function f(na){if(!na)return null;var ia=na.simpleText;return ia?ia:na.runs?g.dq(na.runs,function(Aa){return Aa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,C=null,G=null,F=null,I=null,P=null,Q=null;if("VIDEO"===h)g.S(l,g.KG)?m=g.S(l,g.KG).url:(Q=g.S(l,g.sT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.S(l,g.KG)?m=g.S(l,g.KG).url:(Q=g.S(l,g.sT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=W3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?C=d(b):G=f(b.subscribersText)}else"WEBSITE"===h?((F=W3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(P=f(b.additionalFeesText)),(n=W3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=W3(b,"title","accessibility","accessibilityData","label");var Y=b.endpoint?b.endpoint.clickTrackingParams:null,
ka="";if(b.metadata){var sa=f(b.metadata);sa&&(ka=sa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ka,callToAction:f(b.callToAction),sV:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,JD:p,playlistLength:t,channelId:v,subscribeButton:C,subscribersText:G,isSubscribe:x,vu:m||null,p6:n,sessionData:Y?{itct:Y}:null,qaa:q,nC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:c4(b.impressionUrls||[],b4),c6:c4(b.hovercardShowUrls||[],b4),clickUrls:c4(l.loggingUrls||[],b4),visualElement:g.QF(b.trackingParams),productPrice:I,additionalFeesText:P,watchEndpoint:Q||null}},Nib=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:c4(a.impressionUrls||[],b4),elements:c4(a.elements||[],function(d,e){return Mib(b,d,e)})};
a.trackingParams&&(c.visualElement=g.QF(a.trackingParams));return c},Oib=function(a){g.zV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.S=[];this.ea=!0;this.K=0;a=a.W();this.ma=g.jS(a)||g.lS(a);this.events=new g.aL(this);g.L(this,this.events);this.events.V(this.player,g.rK("creatorendscreen"),this.onCueRangeEnter);this.events.V(this.player,g.sK("creatorendscreen"),this.onCueRangeExit);this.events.V(this.player,"resize",this.Nb);this.events.V(window,"focus",this.O9);this.load();var b=g.of("STYLE");(g.Ye("HEAD")[0]||document.body).appendChild(b);g.ub(this,function(){g.tf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Pib=function(a){return a.player.getVideoData().Sd?"current":a.ma?"new":"current"},d4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Qib=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Nib(f,Pib(a))));e4(a,f)},
urlParams:{v:c},withCredentials:!0};a.ma&&(c.urlParams.ptype="embedded");var d=b.Wx;d&&(c.postParams={ad_tracking:d});if(b=g.qRa(b))if(b=g.Bn(b),b=g.Yd(b))a.C=g.oC(b,c)},e4=function(a,b,c){c=void 0===c?!0:c;
a.player.lf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.S.length&&(a.S.forEach(function(l){l.dispose()}),a.S.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Rib(a);c=[];d=new g.qK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().B||(a.B=new g.T({I:"div",T:"ytp-ce-shadow"}),g.sU(a.player,a.B.element,4),a.D=new g.XG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Sib(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.sU(a.player,f.element,4);var h=new g.qK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Tib(a,f,e)}else g.WF(new g.nD("buildEndscreenElement null",
e))}a.player.wf(c);a.Nb()}},Rib=function(a){var b=g.RF(),c=g.SF();
c&&b&&a.endscreen.visualElement&&g.WB(g.bG)(void 0,c,b,a.endscreen.visualElement)},Sib=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Oa:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-covering-image",Y:f4(b)},{I:"div",T:"ytp-ce-covering-shadow-top"},{I:"a",T:"ytp-ce-covering-overlay",Y:{href:g4(a,b.vu),tabindex:"-1"},X:[{I:"div",Oa:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Hu(b.title||"")},Aa:b.title},{I:"div",T:b.JD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",Aa:b.videoDuration||
void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={I:"div",Oa:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-covering-image",Y:f4(b)},{I:"div",T:"ytp-ce-covering-shadow-top"},{I:"a",T:"ytp-ce-covering-overlay",Y:{href:g4(a,b.vu),tabindex:"-1"},X:[{I:"div",Oa:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Hu(b.title||"")},Aa:b.title},{I:"div",T:"ytp-ce-playlist-count",X:[{I:"div",T:"ytp-ce-playlist-icon"},
{I:"div",T:"ytp-ce-playlist-count-text",Aa:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={I:"div",Oa:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",X:[{I:"div",
T:"ytp-ce-expanding-overlay-body",X:[{I:"div",T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"a",Oa:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:g4(a,b.vu),target:"_blank",tabindex:"-1",dir:g.Hu(b.title||"")},Aa:b.title},b.subscribeButton?{I:"div",T:"ytp-ce-subscribe-container",X:[{I:"div",T:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",T:"ytp-ce-channel-subscribers-text",Aa:b.subscribersText}:"",b.metadata?{I:"div",Oa:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
Aa:b.metadata}:""]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:f4(b)}]};c=new g.T(c);var d=g.Ze(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.nu(d,"ytp-ce-subscribe-button");if(a.player.W().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.lW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.S.push(e)}break;case "WEBSITE":a={I:"div",Oa:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",X:[{I:"div",T:"ytp-ce-expanding-overlay-body",X:[{I:"div",
T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",T:"ytp-ce-website-title",Y:{dir:g.Hu(b.title||"")},Aa:b.title},{I:"div",T:"ytp-ce-website-metadata",Aa:b.metadata},{I:"a",Oa:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:g4(a,b.vu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:f4(b)},{I:"div",T:"ytp-ce-expanding-icon",Y:Uib(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",T:"ytp-ce-merchandise-price-container",
X:[{I:"div",T:"ytp-ce-merchandise-price",Aa:b.productPrice}]},b.additionalFeesText&&c.X.push({I:"div",T:"ytp-ce-merchandise-additional-fees",Aa:b.additionalFeesText})),a={I:"div",Oa:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.nC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",
X:[{I:"div",T:"ytp-ce-expanding-overlay-body",X:[{I:"div",T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",T:"ytp-ce-merchandise-title",Y:{dir:g.Hu(b.title||"")},Aa:b.title},c,{I:"div",T:"ytp-ce-merchandise-metadata",Aa:b.metadata},{I:"a",Oa:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:g4(a,b.vu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:f4(b)},{I:"div",T:"ytp-ce-merchandise-invideo-cta-container",X:[{I:"div",T:"ytp-ce-merchandise-invideo-cta",
Aa:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.nu(c.element,"ytp-ce-placeholder");return c},f4=function(a){if(a.sV)var b=a.sV.thumbnails;
return Uib(b?b[b.length-1].url:null)},Uib=function(a){return a?{style:"background-image: url("+a+")"}:{}},Tib=function(a,b,c){function d(m){m&&(b.Ua("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.V(m,"focus",f),b.V(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.nu(b.element,"ytp-ce-force-expand"),h4(a,c.id,!0)):(g.pu(b.element,"ytp-ce-force-expand"),g.pu(b.element,"ytp-ce-element-hover"),h4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ua("mouseenter",function(){Vib(a,b,c)});
b.Ua("mouseleave",function(){Wib(a,b,c)});
a.player.W().B||b.Ua("click",function(){g.nu(b.element,"ytp-ce-element-hover")});
b.Ua("click",function(m){Xib(a,c,m)});
b.Ua("keypress",function(m){Xib(a,c,m)});
b.Ua("focus",function(){Vib(a,b,c)});
b.Ua("blur",function(){Wib(a,b,c)});
b.Ua("touchstart",function(){Vib(a,b,c)});
var l=g.af("ytp-ce-expanding-overlay-hider",b.element);l&&b.V(l,"touchstart",function(m){m.stopPropagation();g.pu(b.element,"ytp-ce-element-hover");g.pu(b.element,"ytp-ce-force-expand")});
b.Ua("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.af("ytp-sb-subscribe",b.element));d(g.af("ytp-sb-unsubscribe",b.element));b.Ua("focus",f);b.Ua("blur",h)},Xib=function(a,b,c){if(b.vu&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.mu(d,"ytp-ce-element");){g.mu(d,"subscribe-label")&&Yib(a,b);
if(g.mu(d,"ytp-ce-channel-subscribe"))return;d=g.uf(d)}if(!d||g.mu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Wib(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.qaa)Yib(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Bn(g4(a,b.vu)),g.wH(g.Yd(c),void 0,b.sessionData);else{var e=g.vS(a.player.W())||a.player.getVideoData().Sd,f=function(){var h=g4(a,b.vu),l=b.sessionData,m=b.watchEndpoint,n=g.bC(h);e&&n&&(n.v||n.list)?a.player.Ao(n.v,
l,n.list,!1,void 0,m||void 0):g.Xva(h,l)};
Yib(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},g4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.CS(a)+b}else return"";return b},Vib=function(a,b,c){g.mu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.nu(b.element,"ytp-ce-element-hover"):a.player.W().B?(new g.fu(function(){g.nu(b.element,"ytp-ce-element-hover")},200)).start():g.nu(b.element,"ytp-ce-element-hover"),i4(a,c.c6),h4(a,c.id,!0))},Wib=function(a,b,c){g.pu(b.element,"ytp-ce-element-hover");
g.pu(b.element,"ytp-ce-force-expand");h4(a,c.id,!1)},h4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.ru(a.j[e].element,"ytp-ce-element-shadow-show",c)},i4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||d4(a))c&&c();else{b=Zib(a,b);var e=0,f=!1,h=new g.fu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.HE(b[a],d)}},Yib=function(a,b,c){i4(a,b.clickUrls,c);
(a=g.SF())&&b.p6&&g.iG(a,b.visualElement)},Zib=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push($ib(b[d],c));return a},$ib=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},ajb=function(a){return"string"===typeof a?a:""},j4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},bjb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},k4=function(a){return a.value?a.value:null},l4=function(a){if(!a)return null;
var b=g.Bn(ajb(a.value));b=g.Yd(b);if(!b)return null;var c=j4(a.target,cjb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new bjb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},djb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},gjb=function(a){if(!a)return null;
var b=j4(a.type,ejb),c=j4(a.trigger,fjb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=l4(a?a:null);return b?new djb(b,c,a):null},hjb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ijb=function(a,b){return g.Bb(a.action,b)},jjb=function(a,b){this.context=a;
this.j=b},kjb=function(a){return a.customMessage?m4("div","iv-card-message",a.customMessage):""},n4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",T:"iv-card-image",Y:{style:a},X:c}},ljb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(m4("li","",c.value));return{I:"ul",T:"iv-card-meta-info",X:b}},m4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Hu(c);return{I:a,Y:b,Aa:c}},mjb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.xC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.xC+");");c.dir=g.Hu(a.customMessage);var d=[{I:"span",Aa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",T:"iv-card-link-icon"}));return{I:"div",Oa:b,Y:c,X:d}},o4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},njb=function(a,b){this.merchant=a;
this.price=b},ojb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},pjb=function(a,b){return b?b:ojb(a)?"current":"new"},p4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.xb=!1;this.eb=new Map;this.fb=new Map;this.context.J.addEventListener(g.rK("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.sK("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},q4=function(a,b,c,d,e,f,h){a.context.j.Ua(b,"click",function(l){a.SK(c,d,e,f||[],h||0,l)});
a.context.j.Ua(b,"touchstart",function(){a.xb=!1});
a.context.j.Ua(b,"touchmove",function(){a.xb=!0})},qjb=function(a){var b;
return(null==(b=g.S(a,g.KG))?0:b.url)?g.S(a,g.KG).url:(a=g.S(a,g.sT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},r4=function(a,b,c){return{QW:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
f_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},rjb=function(a,b,c){p4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Pa=this.Kb=this.C=this.isInitialized=!1;this.cards=[];this.Ab=this.ma=this.Na=this.G=this.Xa=this.j=null;this.qa=[];this.va=this.S=this.qg=this.Fa=null;this.K=0;this.Ia=new g.fu(function(){},c.Z.Ri?4E3:3E3);
g.L(this,this.Ia);this.rb=new g.fu(function(){});
g.L(this,this.rb);this.Ca=new jjb(c,function(e,f,h,l,m,n){q4(d,e,f,h,l,m,n)});
this.ea=new g.T({I:"div",T:"iv-drawer",Y:{id:"iv-drawer"},X:[{I:"div",T:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{I:"span",T:"iv-drawer-header-text"},{I:"button",Oa:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",T:"iv-drawer-content"}]});g.L(this,this.ea);this.D=this.ea.element;this.kb=new g.XG(this.ea,330);g.L(this,this.kb);this.Qb=g.af("iv-drawer-header-text",this.D);this.B=g.af("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&s4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.C)&&t4(d)});
this.Va=new g.aL(this);g.L(this,this.Va);this.J.addEventListener("videodatachange",this.ot.bind(this))},sjb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){s4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){t4(a)});
var c=b.headerText;g.Df(a.Qb,c);a.ma&&a.ma.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.QF(b.trackingParams);a.S=g.QF(b.closeTrackingParams);a.qg=g.QF(b.iconTrackingParams)},tjb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.W().experiments.qb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.yG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},So:null,zl:e.trackingParams?g.QF(e.trackingParams):null,qg:f&&f.trackingParams?g.QF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
xC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};u4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.yG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:v4(a,c,b,f),sponsored:!1,bj:r4(f,e,f.command),So:f.trackingParams?g.QF(f.trackingParams):null,zl:e.trackingParams?g.QF(e.trackingParams):null,qg:l&&l.trackingParams?g.QF(l.trackingParams):null,imageUrl:w4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.yG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,xC:null,title:f.title?g.yG(f.title):"",customMessage:f.callToAction?g.yG(f.callToAction):"",url:g.S(f.command,g.KG).url?l4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.KG).url}):null,onClickCommand:null};u4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.yG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:v4(a,c,b,e),sponsored:!1,bj:r4(e,f,e.endpoint),So:e.trackingParams?g.QF(e.trackingParams):null,zl:f.trackingParams?g.QF(f.trackingParams):null,qg:l&&l.trackingParams?g.QF(l.trackingParams):null,channelId:g.S(e.endpoint,g.SU).browseId,customMessage:e.customText?g.yG(e.customText):null,dZ:w4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.yG(e.channelName):"",metaInfo:[e.subscriberCountText?g.yG(e.subscriberCountText):""],url:l4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,g.SU).canonicalBaseUrl?g.S(e.endpoint,g.SU).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,g.SU).browseId}),onClickCommand:null};u4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.yG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:v4(a,c,b,e),sponsored:!1,bj:r4(e,f,e.action),So:e.trackingParams?g.QF(e.trackingParams):null,zl:f.trackingParams?g.QF(f.trackingParams):null,qg:l&&l.trackingParams?g.QF(l.trackingParams):null,HF:w4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.yG(e.customMessage):null,playlistVideoCount:g.yG(e.playlistVideoCount),title:e.playlistTitle?g.yG(e.playlistTitle):"",metaInfo:[e.channelName?g.yG(e.channelName):
"",e.videoCountText?g.yG(e.videoCountText):""],url:l4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:qjb(e.action)}),onClickCommand:null};u4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.yG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:v4(a,c,b,e),sponsored:!1,bj:r4(e,f,e.action),So:e.trackingParams?g.QF(e.trackingParams):null,zl:f.trackingParams?g.QF(f.trackingParams):null,qg:l&&l.trackingParams?g.QF(l.trackingParams):null,HF:w4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.yG(e.lengthString):null,customMessage:e.customMessage?g.yG(e.customMessage):null,title:e.videoTitle?g.yG(e.videoTitle):"",metaInfo:[e.channelName?g.yG(e.channelName):
"",e.viewCountText?g.yG(e.viewCountText):""],isLiveNow:!!e.badge,url:l4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:qjb(e.action)}),onClickCommand:null};u4(a,b)}}}}}a.K++},w4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},v4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},vjb=function(a,b){if(b=ujb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.jg.id),g.tf(b.oM),g.Fb(a.cards,b),a.DG(),x4(a)},s4=function(a,b,c){if(!a.C){a.kb.show();
a.Xa=new g.fu(function(){g.nu(a.context.J.getRootNode(),g.cZ.IV_DRAWER_OPEN)},0);
a.Xa.start();a.Va.V(a.B,"mousewheel",function(h){a.Ia.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.SF();d&&a.Fa&&a.S&&g.gG(d,[a.Fa,a.S]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.AX||(f.AX=!0,wjb(a.context.logger,f.jg.bj.QW,b)),d&&g.gG(d,[f.jg.So]);V3(a.J);c&&(a.G=new g.fu(function(){a.Na=a.ma;a.Ab.focus()},330),a.G.start())}},t4=function(a){a.C&&(a.kb.hide(),g.cD(a.Va),g.pu(a.context.J.getRootNode(),g.cZ.IV_DRAWER_OPEN),a.C=!1,V3(a.J),a.G&&a.G.stop(),a.G=new g.fu(function(){a.Na&&(a.Na.focus(),a.Na=null)},330),a.G.start())},yjb=function(a){g.ou(a.Fb(),
[g.cZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.sU(a.J,a.D,5);xjb(a);a.ma=g.af("ytp-cards-button",a.J.getRootNode());a.Ab=g.af("iv-drawer-close-button",a.D);a.isInitialized=!0},xjb=function(a){var b=g.af("iv-drawer-close-button",a.D);
a.context.j.Ua(b,"click",a.i4,a);a.context.j.Ua(a.B,"touchend",function(){a.Ia.start()});
a.context.j.Ua(a.B,"scroll",a.C4,a);a.context.B.subscribe("onHideControls",function(){a.Pa=!0});
a.context.B.subscribe("onShowControls",function(){a.Pa=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Pa=g.mu(a.J.getRootNode(),"ytp-autohide")});
a.qa.push(g.VE("iv-button-shown",a.C6,a));a.qa.push(g.VE("iv-button-hidden",a.B6,a));a.qa.push(g.VE("iv-teaser-shown",a.O0,a));a.qa.push(g.VE("iv-teaser-hidden",a.D6,a));a.qa.push(g.VE("iv-teaser-clicked",a.N0,a))},zjb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.S(b.onClickCommand,g.Web))?void 0:c.targetId)?(a.va=b,!0):!1},Ajb=function(a,b){a.va=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.PPa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.S(h[0],g.yYa))?void 0:d.timeRangeStartMillis)||0,a.va=null,!0}return!1},u4=function(a,b){if(!zjb(a,b)||Ajb(a,b)){var c=Bjb(a,b);
if(c){var d={jg:b,oM:c.element,AX:!1};if(!b.onClickCommand){a.isInitialized||yjb(a);vjb(a,b.id);var e=Cjb(a,d);g.Pb(a.cards,e,0,d);c.Ga(a.B,e);a.DG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,x4(a),Djb(a,d),s4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Ejb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Ejb(a,d)}),x4(a))}}},Bjb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",T:"iv-card-image-text",Aa:b.displayDomain}:void 0;var d=mjb(b);c={I:"div",Oa:["iv-card"],X:[{I:"a",T:"iv-click-target",Y:{href:b.url?k4(b.url)||"":""},X:[n4(b.imageUrl,c),{I:"div",T:"iv-card-content",X:[m4("h2",void 0,b.title),d]}]}]};c=new g.T(c);o4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Oa:["iv-card","iv-card-channel"],X:[{I:"a",Oa:["iv-click-target"],Y:{href:k4(b.url)||"","data-ytid":b.channelId},X:[n4(b.dZ),{I:"div",
T:"iv-card-content",X:[kjb(b),{I:"h2",T:"iv-card-primary-link",Aa:b.title},ljb(b)]}]}]};c=new g.T(c);o4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Oa:["iv-card","iv-card-playlist"],X:[{I:"a",T:"iv-click-target",Y:{href:k4(b.url)||""},X:[n4(b.HF,{I:"div",T:"iv-card-image-overlay",X:[{I:"span",T:"iv-card-playlist-video-count",Aa:b.playlistVideoCount}]}),{I:"div",T:"iv-card-content",X:[kjb(b),m4("h2","iv-card-primary-link",b.title),ljb(b)]}]}]};c=new g.T(c);
o4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=mjb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",T:"iv-card-offer-price",Aa:f.price}),f.merchant&&e.push({I:"div",T:"iv-card-offer-merchant",Aa:f.merchant}),f={I:"div",X:e});e=b.url?k4(b.url)||"":"";c={I:"div",Oa:c,Y:{tabindex:"0"},X:[{I:"a",Oa:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",T:"iv-card-content",X:[b.sponsored?{I:"div",T:"iv-card-sponsored",X:["Sponsored",{I:"div",T:"iv-ad-info-container",X:[{I:"div",T:"iv-ad-info",Aa:"{{adInfo}}"},{I:"div",T:"iv-ad-info-icon-container",X:[{I:"div",T:"iv-ad-info-icon"},{I:"div",T:"iv-ad-info-callout"}]}]}]}:"",{I:"a",T:"iv-click-target",Y:{href:e},X:[m4("h2",d,b.title),f]}]}]};c=new g.T(c);d=g.of("span");g.Df(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.oe(d,"adInfo");o4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",T:"iv-card-video-duration",Aa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Oa:["yt-badge","yt-badge-live"],Aa:"LIVE NOW"}:null;e={I:"div",Oa:["iv-card","iv-card-video"],X:[{I:"a",T:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:k4(c))||""},X:[n4(b.HF,d),{I:"div",T:"iv-card-content",X:[kjb(b),m4("h2","iv-card-primary-link",b.title),ljb(b),f]}]}]};c=new g.T(e);o4(a,g.$e("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Cjb=function(a,b){if(0===a.cards.length)return 0;
a=g.Cb(a.cards,function(c){return b.jg.startMs>c.jg.startMs||b.jg.startMs===c.jg.startMs&&b.jg.timestamp>=c.jg.timestamp?!0:!1});
return-1===a?0:a+1},Fjb=function(a){if(a.j)return"productListing"===a.j.jg.type;
if(a.J.N("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.eq(a.cards,function(c){return"productListing"===c.jg.type})}return g.eq(a.cards,function(c){return"productListing"===c.jg.type})},x4=function(a){g.ru(a.J.getRootNode(),"ytp-cards-shopping-active",Fjb(a))},Ejb=function(a,b){if(!g.mu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.SF(),d=a.j?a.j.jg.qg:a.qg;
c&&d&&g.hG(c,[d]);a.j=b;x4(a)}(c=a.isInitialized&&"none"==a.Fb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.jg.teaserDurationMs&&a.J.ZA(!0,{teaserText:b.jg.teaserText,durationMs:b.jg.teaserDurationMs,onClickCommand:b.jg.onClickCommand});a.rb.isActive()||((!a.C||!a.Ia.isActive()&&a.Pa)&&Djb(a,b),a.rb.start(910+b.jg.teaserDurationMs))}},Djb=function(a,b){a.ea.Ib?(b=new $3([0,
a.B.scrollTop],[0,b.oM.offsetTop],600,Kib),a.context.C.Ua(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ua(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.uG(a.ea,!0),a.B.scrollTop=b.oM.offsetTop,g.uG(a.ea,!1))},y4=function(a){return a.j&&a.j.jg?a.j.jg:a.cards[0]&&a.cards[0].jg?a.cards[0].jg:null},ujb=function(a,b){return g.Bb(a.cards,function(c){return c.jg.id===b})},z4=function(a,b,c){p4.call(this,a,b);
this.annotation=c;this.isActive=!1},Gjb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},A4=function(a,b,c){z4.call(this,a,b,c);
this.B=null;this.S=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Hjb=function(a,b){var c=void 0===c?0:c;
var d=Bib(b).width;g.Kr(b,d);c=new Iib(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Jib);g.L(a,c);a.context.C.Ua(c,"begin",function(){g.Qr(b,!0)});
c.play()},Kjb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Oa:["iv-branding-context-name"],Aa:b.channel_name}),d=a.createElement({I:"div",Oa:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.lW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Ga(d));var f=a.createElement({I:"div",Oa:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Oa:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Qr(h,!1);var l=a.createElement({I:"div",Oa:["branding-context-container-outer"]});l.appendChild(h);g.Er(l,"right",b.image_width+"px");g.qf(a.Fb(),l);a.C=new g.fu(function(){Ijb(a,h,l)},500);
g.L(a,a.C);a.context.j.Ua(a.Fb(),"mouseover",function(){Jjb(a,h,l,f,b.image_height)});
a.context.j.Ua(a.Fb(),"mouseout",function(){a.C.start()})}},Jjb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Pr(b);a.j||(b.style.width=g.Jr(f.width,!0),c.style.width=g.Jr(f.width,!0));g.Er(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Er(d,"right","1px");a.D=!0;g.Qr(b,!0);a.G=new g.fu(function(){g.nu(this.Fb(),"iv-branding-active")},0,a);
a.G.start()}},Ijb=function(a,b,c){g.pu(a.Fb(),"iv-branding-active");
a.K=new g.fu(function(){g.Qr(b,!1);a.j||(c.style.width=g.Jr(0,!0))},250);
a.K.start();a.D=!1},Ljb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Z=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Mjb=function(a,b,c){z4.call(this,a,b,c);
var d=this;this.ma=this.isCollapsed=this.ea=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.S=this.createElement({I:"div",Oa:["iv-promo-contents"]});this.G=new g.fu(function(){d.j.setAttribute("aria-hidden","true");g.Qr(d.C,!1);g.Qr(d.B,!0)},700,this);
g.L(this,this.G)},Pjb=function(a,b,c){c.stopPropagation();
Njb(a);Ojb(a,b);a.j.focus()},Qjb=function(a){a.isCollapsed||a.ma||a.D||(g.nu(a.Fb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Njb=function(a){a.G.stop();
a.isCollapsed&&(g.qu(a.Fb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Qr(a.B,!1),g.Qr(a.C,!0))},Ojb=function(a,b){a.D||(a.D=g.lg(function(){Rjb(this);
Qjb(this)},b,a))},Rjb=function(a){a.D&&(g.Qa.clearTimeout(a.D),a.D=null)},Sjb=function(a){this.J=a},wjb=function(a,b,c){b&&(c?B4(a,b.map(function(d){return g.Vt(d,c)})):B4(a,b))},B4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.HE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Tjb=function(a){g.zV.call(this,a);
var b=this;this.ea=this.S=!1;this.loadNumber=0;this.K={};this.logger=new Sjb(this.player);this.D=new g.aL(this);this.G=this.nx=null;this.events=new g.aL(this);this.wh=this.ma=this.j=null;this.qa=[];g.L(this,this.D);this.D.V(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.D.V(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.D.V(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.D.V(this.player,"resize",function(d){b.ra("resize",d)});
this.D.V(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.P0,this);this.subscribe("resize",this.hJ,this);this.player.W().Pa.subscribe("vast_info_card_add",this.IY,this);g.L(this,this.events);this.va=this.createElement({I:"div",T:"video-custom-annotations"});this.B=new g.T({I:"div",Oa:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.sU(this.player,this.B.element,4);this.B.hide();this.C=new g.T({I:"div",Oa:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",T:"video-annotations"});
a.appendChild(this.va);this.C.element.appendChild(a);this.fu()&&this.load();var c=this.createElement({I:"style"});(g.Ye("HEAD")[0]||document.body).appendChild(c);g.ub(this,function(){g.tf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Ujb=function(a){a=a.createElement({I:"div",
Oa:["annotation","annotation-type-custom"]});g.Qr(a,!1);return a},Vjb=function(a,b){b=!b.isCued()&&!g.cH(b,1024);
g.uG(a.B,b);g.uG(a.C,b)},Wjb=function(a,b,c){a.S=!0;
a.G=g.oC(b,c)},Xjb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Xa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Xjb(a,e))}return c},akb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.W().Pa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.iC(h)&&h.responseXML?h.responseXML:null)&&Yjb(a,h)}};
g.vD()&&(d.onFinish=Zjb(a,d.onFinish));d.postParams={ic_only:"1"};$jb(d,c);a.S=!0;g.oC(b.Xa,d)}}},$jb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.IG&&(a.postParams.ic_coll=b.IG);b.pM&&(a.postParams.ic_xml=b.pM);b.wK&&(a.postParams.ic_track=b.wK)},bkb=function(a){var b=new g.T({I:"div"});
g.Qr(b.element,!1);var c=new rjb(a.player,b.element,C4(a));g.L(c,b);b.Ga(a.B.element);c.xF();return c},dkb=function(a,b){var c,d;
if(b=null==(c=b.Jd)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ea=!0,ckb(a,b),b.headerText&&a.wh&&(c=g.yG(b.headerText),a.wh.setAttribute("title",c))},C4=function(a){if(!a.ma){var b=new Lib(a);
g.L(a,b);var c=new g.ro(a);g.L(a,c);a.ma=new Ljb(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.lj)}return a.ma},Yjb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.SF();if(e){var f=g.RF();f&&g.WB(g.iua)(void 0,e,f,[g.QF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Xjb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=j4(f.type,ekb),p=j4(f.style,fkb),q=ajb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=gjb;if(null==t)var v=null;else if(g.Wa(t)){l=[];for(var x=g.u(t),C=x.next();!C.done;C=x.next()){var G=f(C.value);
G&&l.push(G)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new hjb(m,n,p,v,r):null}else e=null}catch(sa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=Ujb(f),P=null;switch(l.type){case "branding":if(f.player.W().Nd)break;f.B.element.appendChild(I);P=new A4(I,C4(f),l);break;case "promotion":g.sU(f.player,I,4),P=new Mjb(I,C4(f),l)}P&&P.xF();if(f=P)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=bkb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var Q=e&&e.data&&e.data.card_type;
f=e.data;if(Q)switch(l=f.tracking||{},l={QW:l.impression,click:l.click,close:l.close,f_:l.teaser_impression,sK:l.teaser_click},I=f.tracking_params||{},P=null,Q){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.QF(I.card):null,zl:I.teaser?g.QF(I.teaser):null,qg:I.icon?g.QF(I.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,dZ:f.image_url,title:f.title,metaInfo:f.meta_info,url:l4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};u4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.QF(I.card):null,zl:I.teaser?
g.QF(I.teaser):null,qg:I.icon?g.QF(I.icon):null,HF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:l4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};u4(c,e);break;case "productListing":f.signin_url&&(P=l4({target:"current",value:f.signin_url}));Q=[];for(var Y=f.offers||[],ka=0;ka<Y.length;ka++)Q.push(new njb(g.ze(Y[ka].merchant),g.ze(Y[ka].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.QF(I.card):null,zl:I.teaser?g.QF(I.teaser):null,qg:I.icon?g.QF(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,xC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:l4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Wgb:P,Vgb:f.signin_title?f.signin_title:void 0,Ugb:f.signin_message?f.signin_message:void 0,offers:Q,onClickCommand:null};u4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.QF(I.card):
null,zl:I.teaser?g.QF(I.teaser):null,qg:I.icon?g.QF(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,xC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:l4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};u4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.QF(I.card):null,zl:I.teaser?g.QF(I.teaser):null,qg:I.icon?g.QF(I.icon):null,HF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:l4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},u4(c,e)}}else sjb(a.j,e);c=!0}}c&&
(V3(a.player),a.hJ())},ckb=function(a,b){var c=!1;
a.j||(a.j=bkb(a),g.L(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(tjb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.MT(f)||(c=a.j,d=b.headerText?g.yG(b.headerText):"",g.Df(c.Qb,d),c.ma&&c.ma.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.QF(b.trackingParams):null,c.S=b.closeButton.infoCardIconRenderer.trackingParams?g.QF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.qg=b.icon.infoCardIconRenderer.trackingParams?g.QF(b.icon.infoCardIconRenderer.trackingParams):null,a.hJ());V3(a.player)}},gkb=function(a,b,c,d,e){if(!a.player.W().Nd){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,g.SU)&&g.S(b.navigationEndpoint,g.SU).browseId&&f.push(new djb("openUrl","click",new bjb("/channel/"+g.S(b.navigationEndpoint,g.SU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.FT)){d.channel_id=g.S(b.subscribeButton,g.FT).channelId;var l;b=g.S(b.subscribeButton,g.FT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.yG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.yG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.yG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.yG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.S(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.M2))?void 0:m.url)||"";l={subscribeText:g.yG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.yG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new hjb(c,"branding","branding",f,d);l=Ujb(a);a.B.element.appendChild(l);f=new A4(l,C4(a),f);f.xF();g.L(f,f);a.K[c]=f}},Zjb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.isDisposed()||a.qa.push(g.Yt.Ni(function(){b.apply(null,g.pa(c))}))}},hkb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.kU.prototype.ZA=g.ba(19,function(a,b){var c=g.QV(this.Gb());c&&c.ZA(a,b)});
var X3={},Y3=null;g.gb($3,g.Du);g.k=$3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;Z3(this);this.startTime=a=g.eb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.YI();this.gm("play");this.isPaused()&&this.gm("resume");this.j=1;var b=g.ab(this);b in X3||(X3[b]=this);Eib();Fib(this,a);return!0};
g.k.stop=function(a){Z3(this);this.j=0;a&&(this.progress=1);Gib(this,this.progress);this.gm("stop");this.rr()};
g.k.pause=function(){this.isPlaying()&&(Z3(this),this.j=-1,this.gm("pause"))};
g.k.Ba=function(){0==this.j||this.stop(!1);this.gm("destroy");$3.Qf.Ba.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.RK=function(){this.gm("animate")};
g.k.gm=function(a){this.dispatchEvent(new Hib(a,this))};
g.gb(Hib,g.xb);g.gb(a4,$3);a4.prototype.C=function(){};
a4.prototype.RK=function(){this.C();a4.Qf.RK.call(this)};
a4.prototype.rr=function(){this.C();a4.Qf.rr.call(this)};
a4.prototype.YI=function(){this.C();a4.Qf.YI.call(this)};
g.gb(Iib,a4);Iib.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Lib,g.J);g.k=Lib.prototype;g.k.Ua=function(a,b,c,d){c=(0,g.cb)(c,d||this.B);a=g.XC(a,b,c);this.j.push(a);return a};
g.k.vI=function(a,b,c,d){c=(0,g.cb)(c,d||this.B);a=Cib(a,b,c);this.j.push(a);return a};
g.k.Rc=function(a){g.YC(a);g.Fb(this.j,a)};
g.k.Nf=function(){g.YC(this.j);this.j.length=0};
g.k.Ba=function(){this.Nf();g.J.prototype.Ba.call(this)};g.w(Oib,g.zV);g.k=Oib.prototype;g.k.load=function(){g.zV.prototype.load.call(this);if(!d4(this)){var a=g.rRa(this.player.getVideoData());a?(a=Nib(a,Pib(this)),e4(this,a,!1)):Qib(this)}};
g.k.unload=function(){e4(this,null);this.C&&(this.C.abort(),this.C=null);g.zV.prototype.unload.call(this)};
g.k.Mh=function(a,b){return d4(this)?"loadCustomEndscreenRenderer"===a?(a=Nib(b,"new"),e4(this,a),!0):null:null};
g.k.getOptions=function(){return d4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Nb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ikb.length;f++){var h=Math.abs(b.width-ikb[f]);if(-1===e||d>=h)e=f,d=h}d=jkb[e];this.B&&g.Er(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Or(e.element,m,f);g.Kr(e.element,n,p);g.qu(e.element,kkb);256<m||256<f?g.nu(e.element,"ytp-ce-large-round"):96<m||96<f?g.nu(e.element,"ytp-ce-medium-round"):g.nu(e.element,"ytp-ce-small-round");g.qu(e.element,lkb);m=h.left+h.width/2;h=h.top+l/2;g.nu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qu(e.element,jkb);g.nu(e.element,d);(e=g.Ze(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Er(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())i4(this,this.endscreen.impressionUrls),(a=g.SF())&&this.endscreen.visualElement&&g.fG(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.nu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.nu(b,"ytp-ce-shown");i4(this,c.impressionUrls);(b=g.SF())&&g.fG(b,c.visualElement);this.player.W().K&&this.player.Ta("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.pu(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.pu(b,"ytp-ce-shown");this.player.W().K&&this.player.Ta("endscreenelementhidden",a)}};
g.k.O9=function(a){var b=this;a.target===window&&(new g.fu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.qu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ikb=[346,426,470,506,570,640,853,1280,1920],jkb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),lkb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],kkb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var cjb={Bqa:"current",uQa:"new"};var ejb={CLOSE:"close",VTa:"openUrl",SUBSCRIBE:"subscribe"},fjb={dpa:"click",CLOSE:"close",WBa:"hidden",VYa:"rollOut",WYa:"rollOver",C_a:"shown"};hjb.prototype.gf=function(){var a=ijb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var fkb={Yja:"anchored",n0:"branding",CHANNEL:"channel",rqa:"cta",ZBa:"highlightText",aGa:"label",PLAYLIST:"playlist",tWa:"popup",z2a:"speech",SUBSCRIBE:"subscribe",N5a:"title",VIDEO:"video",acb:"website"},ekb={n0:"branding",Xma:"card",Esa:"drawer",YBa:"highlight",bMa:"marker",QXa:"promotion",TEXT:"text",Bdb:"widget"};g.w(p4,g.J);g.k=p4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.qK(a,b,{id:c,namespace:"annotations_module"});d&&this.eb.set(a,d);e&&this.fb.set(a,e);this.context.J.wf([a])};
g.k.xF=function(){this.context.B.subscribe("resize",this.DG,this)};
g.k.Fb=function(){return this.element};
g.k.SK=function(a,b,c,d,e,f){if(this.xb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.tf(this.Fb())};
g.k.DG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=k4(a);if(f){var h=pjb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Sd||!1,n=g.bC(f||"");m&&n&&(n.v||n.list)?e.context.J.Ao(n.v,b,n.list,!1):g.wH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);B4(this.context.logger,c,l,d);ojb(f)||(c=g.SF(),d=b.itct,c&&d&&g.iG(c,g.QF(d)))}};
g.k.Ba=function(){this.eb.clear();this.fb.clear();g.J.prototype.Ba.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.L(this,a);return a.element};g.w(rjb,p4);g.k=rjb.prototype;g.k.ot=function(){this.va&&u4(this,this.va)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Pr(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.DG=function(){var a=this.isAvailable();g.Qr(this.Fb(),a);g.ru(this.context.J.getRootNode(),g.cZ.IV_DRAWER_ENABLED,a);V3(this.J)};
g.k.destroy=function(){this.J.ZA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.WE(this.qa);g.cD(this.Va);this.Xa&&this.Xa.dispose();this.G&&this.G.dispose();p4.prototype.destroy.call(this)};
g.k.i4=function(){if(this.C){B4(this.context.logger,y4(this).bj.close);var a=g.SF();a&&this.S&&g.iG(a,this.S);t4(this)}};
g.k.C4=function(){g.ru(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.C6=function(){var a=g.SF(),b=y4(this);b=b?b.qg:this.qg;a&&b&&g.gG(a,[b])};
g.k.B6=function(){var a=g.SF(),b=y4(this);b=b?b.qg:this.qg;a&&b&&g.hG(a,[b])};
g.k.O0=function(){var a=y4(this);B4(this.context.logger,a.bj.f_);var b=g.SF();b&&a&&g.gG(b,[a.zl,a.qg])};
g.k.D6=function(){var a=g.SF(),b=y4(this);a&&b&&g.hG(a,[b.zl])};
g.k.N0=function(a){var b=y4(this),c=g.SF();this.j?a?(a=this.context.logger,B4(a,b.bj.sK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.zl&&g.iG(c,b.zl)):(a=this.context.logger,B4(a,b.bj.sK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.qg&&g.iG(c,b.qg)):(a=this.context.logger,B4(a,b.bj.sK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.qg&&g.iG(c,this.qg))};g.w(z4,p4);z4.prototype.xF=function(){p4.prototype.xF.call(this);Gjb(this)};
z4.prototype.show=function(){p4.prototype.show.call(this);var a=g.SF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.gG(a,[g.QF(b.itct)])};
z4.prototype.hide=function(){p4.prototype.hide.call(this);var a=g.SF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.hG(a,[g.QF(b.itct)])};g.w(A4,z4);A4.prototype.Ow=function(){g.nu(this.Fb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Oa:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Qr(this.B,!1);var b=this.createElement({I:"button",Oa:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Fb().appendChild(b);var c=this.annotation.gf();c&&q4(this,b,c,this.annotation.id,a.session_data);Kjb(this,a)};
A4.prototype.show=function(){if(!this.isActive&&(z4.prototype.show.call(this),this.S||(this.Ow(),this.S=!0),g.Qr(this.Fb(),!0),this.isActive=!0,this.B)){try{Hjb(this,this.B)}catch(a){}g.nu(this.context.J.getRootNode(),"ytp-branding-shown")}};
A4.prototype.hide=function(){this.isActive&&(z4.prototype.hide.call(this),g.Qr(this.Fb(),!1),this.isActive=!1,g.pu(this.context.J.getRootNode(),"ytp-branding-shown"))};
A4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);z4.prototype.destroy.call(this)};g.w(Mjb,z4);g.k=Mjb.prototype;
g.k.Ow=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Fb().setAttribute("aria-hidden","true");this.Fb().setAttribute("aria-label","Promotion");this.Fb().tabIndex=0;var e=this.annotation.gf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Oa:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",T:"iv-promo-video-duration",Aa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",T:"iv-promo-playlist-length",Aa:b.playlist_length.toString()}),h.appendChild(f));e&&q4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",T:"iv-promo-txt"}),g.Cn(f,k4(e)),this.j=f):this.j=this.createElement({I:"div",T:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",X:[{I:"strong",Aa:b.text_line_1}]});var m=this.createElement({I:"p",X:[{I:"span",T:"iv-promo-link",Aa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Oa:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Oa:["iv-button","iv-promo-button"],X:[{I:"span",T:"iv-button-content",Aa:f}]});var p=this.createElement({I:"div",T:"iv-promo-button-container"});p.appendChild(f);e&&q4(this,
this.Fb(),e,this.annotation.id,b.session_data,void 0,c)}g.nu(this.j,"iv-click-target");e&&q4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",X:[{I:"span",Aa:b.text_line_1}]}),m=this.createElement({I:"p",X:[{I:"strong",Aa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Oa:["yt-badge","iv-promo-badge-live"],Aa:"LIVE NOW"})),g.nu(this.j,"iv-click-target"),e&&q4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.S.appendChild(this.j);p&&this.S.appendChild(p);c=this.createElement({I:"div",T:"iv-promo-actions"});this.B=this.createElement({I:"button",Oa:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ua(this.B,"click",function(q){Pjb(a,5E3,q)});
c.appendChild(this.B);g.Qr(this.B,!1);this.context.j.Ua(this.Fb(),"mouseover",this.D5,this);this.context.j.Ua(this.Fb(),"mouseout",this.C5,this);this.context.j.Ua(this.Fb(),"touchend",function(q){Pjb(a,5E3,q)});
this.C=this.createElement({I:"button",Oa:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ua(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.y5:this.x5,this);c.appendChild(this.C);g.ou(this.Fb(),d);h&&(g.qf(this.Fb(),h),n&&h.appendChild(n));g.qf(this.Fb(),this.S);g.qf(this.Fb(),c)};
g.k.show=function(){this.isActive||(z4.prototype.show.call(this),this.ea||(this.Ow(),this.ea=!0),g.Qr(this.Fb(),!0),g.lg(function(){g.pu(this.Fb(),"iv-promo-inactive")},100,this),this.Fb().removeAttribute("aria-hidden"),this.isActive=!0,Rjb(this),Njb(this),Ojb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.nu(this.Fb(),"iv-promo-inactive"),this.isActive=!1,this.Fb().setAttribute("aria-hidden","true"))};
g.k.SK=function(a,b,c,d,e,f){return this.isCollapsed?!1:z4.prototype.SK.call(this,a,b,c,d,e,f)};
g.k.D5=function(a){this.ma=!0;Pjb(this,500,a)};
g.k.C5=function(){this.ma=!1;Qjb(this)};
g.k.x5=function(a){a.stopPropagation();this.hide()};
g.k.y5=function(a){a.stopPropagation();Rjb(this);this.isCollapsed=!0;g.nu(this.Fb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();z4.prototype.destroy.call(this)};g.w(Tjb,g.zV);g.k=Tjb.prototype;g.k.Mh=function(a,b){if(!hkb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.r2(b))&&Yjb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(vjb(this.j,b),V3(this.player)),!0}return null};
g.k.getOptions=function(){return hkb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.fu=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Sd&&a.qa||g.iU(this.player.app)?!1:1===c&&!b.qU||a.Pa.get(b.videoId)||g.NT(b)||g.sRa(b)?!0:!1};
g.k.hJ=function(){if(this.C){var a=this.player.tb().getVideoContentRect(!0);g.Or(this.C.element,a.width,a.height);g.Kr(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Rk();a=this.j;b=b.width;g.ru(a.D,"iv-drawer-small",426>=b);g.ru(a.D,"iv-drawer-big",1280<=b)}};
g.k.P0=function(a){Vjb(this,a.state);g.cH(a.state,2)&&(this.Gk()&&this.Ro()&&2!==this.player.getPresentingPlayerType()&&this.aB(!1),this.ZA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.iC(h)&&h.responseXML?h.responseXML:null)&&(Yjb(b,h),g.nu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.zV.prototype.load.call(this);Vjb(this,this.player.Vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.vD()&&(a=Zjb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Pa.get(d);f&&$jb(e,f);f=f&&(f.pM||f.IG);if(!c.yx||f)c.Xa?Wjb(this,c.Xa,e):(this.nx=function(){if(!b.S)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.MT(h))&&!b.ea&&dkb(b,h)},this.player.addEventListener("videodatachange",this.nx));
g.sU(this.player,this.C.element,4);this.hJ();(f=g.NT(c))&&ckb(this,f);(f=g.sRa(c))&&f.featuredChannel&&gkb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.wh=g.af("ytp-cards-button",this.player.getRootNode());g.MT(c)&&dkb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&Wjb(this,b.Xa,a)};
g.k.unload=function(){this.player.lf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.ma=null;this.j&&(this.j.destroy(),this.j=null,V3(this.player));this.S=!1;this.G&&(this.G.abort(),this.G=null);this.ea=!1;this.K={};this.B.hide();g.zV.prototype.unload.call(this);this.C.detach();this.nx&&(this.player.removeEventListener("videodatachange",this.nx),this.nx=null)};
g.k.IY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?akb(this):this.load())};
g.k.Gk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.Ro=function(){return!!this.j&&this.j.C};
g.k.aB=function(a,b,c){b=void 0===b?!1:b;this.Gk();this.j&&(a?c?s4(this.j,c,b):s4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):t4(this.j))};
g.k.ZA=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.Ba=function(){this.player.W().Pa.unsubscribe("vast_info_card_add",this.IY,this);g.pu(this.player.getRootNode(),g.cZ.IV_DRAWER_OPEN);for(var a=this.qa,b=g.Yt,c=0,d=a.length;c<d;c++)b.Mj(a[c]);this.qa.length=0;g.zV.prototype.Ba.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.L(this,a);return a.element};g.yV("annotations_module",Tjb);g.yV("creatorendscreen",Oib);})(_yt_player);
